### ISSUE TITLE
Error if output folder does not exist

### ISSUE THREAD

**Issue by bojanpavlovic96** [vinhloc1996/Decrypt-PluralSight-Videos#11]
Perhaps it should create output folder instead of throwing an error, plus error thrown does not indicate that output folder is the one that is missing.

**Comment by vinhloc1996** [comment]
Hi @bojanpavlovic96, thanks for announcing the problem. I've fixed it and released version 1.2. Now it will create the output folder if it doesn't exist instead of throwing the exception. You can download the build version 1.2 [here](https://github.com/vinhloc1996/Decrypt-PluralSight-Videos/releases/tag/1.2.0.0) or you can pull the lasted commit in the master repository. Thanks again.
