### ISSUE TITLE
Re-opening Some videos are duplicated and some are missing

### ISSUE THREAD

**Issue by josephDoss2016** [vinhloc1996/Decrypt-PluralSight-Videos#12]
I have downloaded the latest build exe and this issue still exist. 

Description: At random , in every course module, there may exist 2 or 3 files with different names, yet the video is the same. by checking the size of the video and the length of the video, you can easily see it.

To recreate the issue, download ANY video, run program, and check every module directory with duplicate videos by checking size and length of video and opening the videos.

I LOVE this program, but because of this issue, lots of videos are missing after the download
Hope you can fix this issue quickly.

Thanks

**Comment by vinhloc1996** [comment]
Hi @josephDoss2016, sorry for this inconvenience issue. As I said before in the original issue [here](https://github.com/vinhloc1996/Decrypt-PluralSight-Videos/issues/6#issuecomment-453897628). This may randomly happen. I've tested it and no course was neither missed nor duplicated. So currently, the solution may disable the multithreading function, and let the decryption go synchronous. This may solve the issue but it also causes slow down the decryption process. I've continued testing this and finding the solution if it continues happening. Could you provide the command you have run, the course link you have downloaded? Thank you.

**Comment by josephDoss2016** [comment]
I have tested this with many courses with many different PC and in every course you will find a module where the videos may appear different because they have different name but when you open it , it is the same as another video within the module. The clue is that they have the same size and length. It does happen at random between module but in all the courses i downloaded i find evidence in this happening at least once in one of the modules. I tried it in 3 different PCs Windows 10 and 2 virtual machines and it is happening to all. 

Example: https://app.pluralsight.com/library/courses/groovy-fundamentals/table-of-contents

Command: DecryptPluralSightVideos /F "C:\Users\myuser\AppData\Local\Pluralsight\courses" /DB "C:\Users\myuser\AppData\Local\Pluralsight\pluralsight.db"

**Comment by vinhloc1996** [comment]
Hi @josephDoss2016, thanks for providing the evidence. So the issue cause by multithread working. If you disable the multithread function as this [instruction](https://github.com/vinhloc1996/Decrypt-PluralSight-Videos/issues/6#issuecomment-464551761), is it still happen? I will figure it out and determine to shut the multithread down. Through this would cause slow down the decryption process. Sorry for letting this issue happened again.

**Comment by vinhloc1996** [comment]
Hi @josephDoss2016, after testing 10 courses, I've found this issue and it repeats almost every course. I'm sorry for not testing this in the first time reported, this should be fixed in the original issue post. The only solution I have now is to disable the multithread functional. I've published the build version 1.3 [here](https://github.com/vinhloc1996/Decrypt-PluralSight-Videos/releases/tag/1.3.0.0) or you can clone/pull the newest source code to fix this problem. I will try to find another multithreading solution to fix this issue and increase the time of decryption. If you find this issue still exist in the lasted source, please reopen this issue and announce me. Thanks again @josephDoss2016.
